<?php

/*
 *
 * (c) Alexandr Timofeev <tim31al@gmail.com>
 *
 */

namespace App\Tests;

use App\Model\MySqlTestModel;
use App\Model\RedisTestModel;
use App\Utils\Config;
use PHPUnit\Framework\TestCase;
use Psr\Container\ContainerInterface;
use Redis;

class ContainerTest extends TestCase
{
    private ContainerInterface $container;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->container = Config::getContainer();
    }

    public function testInstanceContainer(): void
    {
        $this->assertInstanceOf(ContainerInterface::class, $this->container);
    }

    public function testContainsPDO(): void
    {
        $pdo = $this->container->get(\PDO::class);
        $this->assertInstanceOf(\PDO::class, $pdo);
    }

    public function testContainsRedis(): void
    {
        $redis = $this->container->get(Redis::class);
        $this->assertInstanceOf(Redis::class, $redis);
    }

    public function testContainsMysqlTestModel(): void
    {
        $model = $this->container->get(MySqlTestModel::class);
        $this->assertInstanceOf(MySqlTestModel::class, $model);
    }

    public function testContainsRedisTestModel(): void
    {
        $model = $this->container->get(RedisTestModel::class);
        $this->assertInstanceOf(RedisTestModel::class, $model);
    }
}
